version: "3.8"

services:
  api:
    build: backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend:/app

  ui:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - api
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
